import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Sites 运行在 Cloudflare Workers 兼容环境中。
// 这个脚本把已经验证过的静态前端文件编码进一个 Worker，部署时不需要服务器、
// Node.js 或数据库；浏览器拿到页面后，概率和 EV 仍然由 Rust WebAssembly 计算。
const deployDirectory = dirname(fileURLToPath(import.meta.url));
const webDirectory = resolve(deployDirectory, "..");

const assetDefinitions = [
  ["/index.html", "index.html", "text/html; charset=utf-8"],
  ["/styles.css", "styles.css", "text/css; charset=utf-8"],
  ["/app.js", "app.js", "text/javascript; charset=utf-8"],
  ["/replay-worker.js", "replay-worker.js", "text/javascript; charset=utf-8"],
  ["/pkg/game_ev_engine.js", "pkg/game_ev_engine.js", "text/javascript; charset=utf-8"],
  ["/pkg/game_ev_engine_bg.wasm", "pkg/game_ev_engine_bg.wasm", "application/wasm"],
];

const assets = {};

for (const [urlPath, sourcePath, contentType] of assetDefinitions) {
  const contents = await readFile(resolve(webDirectory, sourcePath));
  assets[urlPath] = {
    contentType,
    // 所有文件统一使用 Base64，避免二进制 WASM 在生成 JavaScript 时损坏。
    base64: contents.toString("base64"),
  };
}

const workerSource = `// Generated by web/deploy/build-worker.mjs. Do not edit by hand.
const ASSETS = ${JSON.stringify(assets)};

function decodeBase64(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);

  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }

  return bytes;
}

export default {
  async fetch(request) {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method Not Allowed", {
        status: 405,
        headers: { Allow: "GET, HEAD" },
      });
    }

    const url = new URL(request.url);
    const requestedPath = url.pathname === "/" ? "/index.html" : url.pathname;
    const asset = ASSETS[requestedPath];

    if (!asset) {
      return new Response("Not Found", { status: 404 });
    }

    const headers = new Headers({
      "Content-Type": asset.contentType,
      // 首页、JavaScript 与 WASM 必须来自同一个部署版本。
      // no-cache 仍允许浏览器保留副本，但每次访问都会确认资源是否变化，
      // 避免发布后出现“新 HTML + 旧 JS/WASM”的混合状态。
      "Cache-Control": "no-cache",
      "X-Content-Type-Options": "nosniff",
    });

    return new Response(
      request.method === "HEAD" ? null : decodeBase64(asset.base64),
      { status: 200, headers },
    );
  },
};
`;

const outputPath = resolve(webDirectory, "dist/server/index.js");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, workerSource, "utf8");

console.log(`Built Sites Worker: ${outputPath}`);
